name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # 每 12 小時更新一次
  workflow_dispatch:          # 允許手動觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python scripts/gen_stats.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_1 }}

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add *.svg
          git commit -m "Update stats images"
          git push
